//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class academico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public academico()
        {
            this.constancias = new HashSet<constancia>();
            this.participacions = new HashSet<participacion>();
            this.productoacademicoes = new HashSet<productoacademico>();
            this.proyectocampoes = new HashSet<proyectocampo>();
            this.trabajorecepcionals = new HashSet<trabajorecepcional>();
        }
    
        public int idAcademico { get; set; }
        public string nombre { get; set; }
        public string numeroPersonal { get; set; }
        public string fechaContratacion { get; set; }
        public Nullable<int> idAreaAcademica { get; set; }
        public Nullable<int> idTipoPersonal { get; set; }
    
        public virtual areaacademica areaacademica { get; set; }
        public virtual tipopersonal tipopersonal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<constancia> constancias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<participacion> participacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productoacademico> productoacademicoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proyectocampo> proyectocampoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trabajorecepcional> trabajorecepcionals { get; set; }
    }
}
