//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class academico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public academico()
        {
            this.Constancia = new HashSet<Constancia>();
            this.Participacion = new HashSet<Participacion>();
            this.ProductoAcademico = new HashSet<ProductoAcademico>();
            this.ProyectoCampo = new HashSet<ProyectoCampo>();
            this.TrabajoRecepcional = new HashSet<TrabajoRecepcional>();
            this.ExperienciaEducativa = new HashSet<ExperienciaEducativa>();
        }
    
        public int IdAcademico { get; set; }
        public string Nombre { get; set; }
        public string NumeroPersonal { get; set; }
        public string FechaContratacion { get; set; }
        public string TipoContratacion { get; set; }
        public int IdPrograma { get; set; }
    
        public virtual ProgramaEducativo ProgramaEducativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Constancia> Constancia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participacion> Participacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoAcademico> ProductoAcademico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoCampo> ProyectoCampo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrabajoRecepcional> TrabajoRecepcional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExperienciaEducativa> ExperienciaEducativa { get; set; }
    }
}
