//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Academico()
        {
            this.Constancia = new HashSet<Constancia>();
            this.Participacion = new HashSet<Participacion>();
            this.ProductoAcademico = new HashSet<ProductoAcademico>();
            this.ProyectoCampo = new HashSet<ProyectoCampo>();
            this.TrabajoRecepcional = new HashSet<TrabajoRecepcional>();
            this.ExperienciaEducativa = new HashSet<ExperienciaEducativa>();
        }
    
        public int IdAcademico { get; set; }
        public string Nombre { get; set; }
        public string NumeroPersonal { get; set; }
        public string FechaContratacion { get; set; }
        public string TipoContratacion { get; set; }
        public int IdPrograma { get; set; }
        public string AreaAcademica { get; set; }
    
        public virtual ProgramaEducativo ProgramaEducativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Constancia> Constancia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participacion> Participacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoAcademico> ProductoAcademico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoCampo> ProyectoCampo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrabajoRecepcional> TrabajoRecepcional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExperienciaEducativa> ExperienciaEducativa { get; set; }
    }
}
