//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class constancia
    {
        public int idConstancia { get; set; }
        public string fechaExpedicion { get; set; }
        public Nullable<int> idTipoConstancia { get; set; }
        public Nullable<int> idAcademico { get; set; }
        public string firmaElectronica { get; set; }
    
        public virtual academico academico { get; set; }
        public virtual tipoconstancia tipoconstancia { get; set; }
    }
}
