//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConstanciasEntities : DbContext
    {
        public ConstanciasEntities()
            : base("name=ConstanciasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academico> Academico { get; set; }
        public virtual DbSet<Administrativa> Administrativa { get; set; }
        public virtual DbSet<Constancia> Constancia { get; set; }
        public virtual DbSet<ExperienciaEducativa> ExperienciaEducativa { get; set; }
        public virtual DbSet<Participacion> Participacion { get; set; }
        public virtual DbSet<ProductoAcademico> ProductoAcademico { get; set; }
        public virtual DbSet<ProgramaEducativo> ProgramaEducativo { get; set; }
        public virtual DbSet<ProyectoCampo> ProyectoCampo { get; set; }
        public virtual DbSet<TrabajoRecepcional> TrabajoRecepcional { get; set; }
    }
}
