//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class constancia
    {
        public int idConstancia { get; set; }
        public string fechaExpedicion { get; set; }
        public Nullable<int> idTipoConstancia { get; set; }
        public Nullable<int> idAcademico { get; set; }
        public string firmaElectronica { get; set; }
    
        public virtual academico academico { get; set; }
        public virtual tipoconstancia tipoconstancia { get; set; }
    }
}
