//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gestionconstanciasEntities : DbContext
    {
        public gestionconstanciasEntities()
            : base("name=gestionconstanciasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<academico> academicoes { get; set; }
        public virtual DbSet<areaacademica> areaacademicas { get; set; }
        public virtual DbSet<constancia> constancias { get; set; }
        public virtual DbSet<experienciaeducativa> experienciaeducativas { get; set; }
        public virtual DbSet<participacion> participacions { get; set; }
        public virtual DbSet<periodo> periodoes { get; set; }
        public virtual DbSet<productoacademico> productoacademicoes { get; set; }
        public virtual DbSet<programaeducativo> programaeducativoes { get; set; }
        public virtual DbSet<proyectocampo> proyectocampoes { get; set; }
        public virtual DbSet<rolacademico> rolacademicoes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tipoconstancia> tipoconstancias { get; set; }
        public virtual DbSet<tipoparticipacion> tipoparticipacions { get; set; }
        public virtual DbSet<tipopersonal> tipopersonals { get; set; }
        public virtual DbSet<tipoproducto> tipoproductoes { get; set; }
        public virtual DbSet<tipopublicacion> tipopublicacions { get; set; }
        public virtual DbSet<tipotrabajo> tipotrabajoes { get; set; }
        public virtual DbSet<trabajorecepcional> trabajorecepcionals { get; set; }
    }
}
