//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class experienciaeducativa
    {
        public int idExperienciaEducativa { get; set; }
        public string nombre { get; set; }
        public string sec { get; set; }
        public Nullable<int> creditos { get; set; }
        public Nullable<int> horasPracticas { get; set; }
        public Nullable<int> horasTeoricas { get; set; }
        public Nullable<int> idProgramaEducativo { get; set; }
    
        public virtual programaeducativo programaeducativo { get; set; }
    }
}
