//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperienciaEducativa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExperienciaEducativa()
        {
            this.Academico = new HashSet<Academico>();
            this.ProgramaEducativo2 = new HashSet<ProgramaEducativo>();
        }
    
        public int IdExperienciaEducativa { get; set; }
        public string Nombre { get; set; }
        public string ProgramaEducativo { get; set; }
        public Nullable<int> IdPrograma { get; set; }
    
        public virtual ProgramaEducativo ProgramaEducativo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Academico> Academico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramaEducativo> ProgramaEducativo2 { get; set; }
    }
}
