//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperienciaEducativa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExperienciaEducativa()
        {
            this.Academico = new HashSet<Academico>();
            this.ProgramaEducativo2 = new HashSet<ProgramaEducativo>();
        }
    
        public int IdExperienciaEducativa { get; set; }
        public string Nombre { get; set; }
        public string ProgramaEducativo { get; set; }
        public Nullable<int> IdPrograma { get; set; }
    
        public virtual ProgramaEducativo ProgramaEducativo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Academico> Academico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramaEducativo> ProgramaEducativo2 { get; set; }
    }
}
