//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participacion
    {
        public int IdParticipacion { get; set; }
        public string PeriodoParticipacion { get; set; }
        public string TipoParticipacion { get; set; }
        public Nullable<int> IdPrograma { get; set; }
        public Nullable<int> IdAcademico { get; set; }
    
        public virtual Academico Academico { get; set; }
        public virtual ProgramaEducativo ProgramaEducativo { get; set; }
    }
}
