//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class participacion
    {
        public int idProyectoCampo { get; set; }
        public string nombre { get; set; }
        public Nullable<int> idPeriodo { get; set; }
        public Nullable<int> idTipoParticipacion { get; set; }
        public Nullable<int> idProgramaEducativo { get; set; }
        public Nullable<int> idAcademico { get; set; }
    
        public virtual academico academico { get; set; }
        public virtual periodo periodo { get; set; }
        public virtual programaeducativo programaeducativo { get; set; }
        public virtual tipoparticipacion tipoparticipacion { get; set; }
    }
}
