//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoAcademico
    {
        public int IdProducto { get; set; }
        public string Titulo { get; set; }
        public string Tipo { get; set; }
        public string TipoPublicacion { get; set; }
        public string FechaPublicacion { get; set; }
        public Nullable<int> IdAcademico { get; set; }
    
        public virtual Academico Academico { get; set; }
    }
}
