//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class productoacademico
    {
        public int idProducto { get; set; }
        public string fechaPublicacion { get; set; }
        public string titulo { get; set; }
        public Nullable<int> idTipoProducto { get; set; }
        public Nullable<int> idTipoPublicacion { get; set; }
        public Nullable<int> idAcademico { get; set; }
    
        public virtual academico academico { get; set; }
        public virtual tipoproducto tipoproducto { get; set; }
        public virtual tipopublicacion tipopublicacion { get; set; }
    }
}
