//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoAcademico
    {
        public int IdProducto { get; set; }
        public string Titulo { get; set; }
        public string Tipo { get; set; }
        public string TipoPublicacion { get; set; }
        public string FechaPublicacion { get; set; }
        public Nullable<int> IdAcademico { get; set; }
    
        public virtual Academico Academico { get; set; }
    }
}
