//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class programaeducativo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public programaeducativo()
        {
            this.experienciaeducativas = new HashSet<experienciaeducativa>();
            this.participacions = new HashSet<participacion>();
        }
    
        public int idProgramaEducativo { get; set; }
        public string nombre { get; set; }
        public string fecha { get; set; }
        public Nullable<int> idAreaAcademica { get; set; }
    
        public virtual areaacademica areaacademica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<experienciaeducativa> experienciaeducativas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<participacion> participacions { get; set; }
    }
}
