//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoCampo
    {
        public int IdProyectoCampo { get; set; }
        public string NombreProyecto { get; set; }
        public string LugarRealizacion { get; set; }
        public string Periodo { get; set; }
        public string RolAcademico { get; set; }
        public Nullable<int> IdAcademico { get; set; }
    
        public virtual Academico Academico { get; set; }
    }
}
