//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrabajoRecepcional
    {
        public int IdTrabajoRecepcional { get; set; }
        public string Titulo { get; set; }
        public string NombreEstudiante { get; set; }
        public string FechaPresentacion { get; set; }
        public string TipoTrabajo { get; set; }
        public int IdAcademico { get; set; }
        public string RolAcademico { get; set; }
    
        public virtual Academico Academico { get; set; }
    }
}
