//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class trabajorecepcional
    {
        public int idTrabajoRecepcional { get; set; }
        public string nombreEstudiante { get; set; }
        public string titulo { get; set; }
        public string infraestructuraOpcional { get; set; }
        public Nullable<int> idAcademico { get; set; }
        public Nullable<int> idTipoTrabajo { get; set; }
    
        public virtual academico academico { get; set; }
        public virtual tipotrabajo tipotrabajo { get; set; }
    }
}
