//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class trabajorecepcional
    {
        public int idTrabajoRecepcional { get; set; }
        public string nombreEstudiante { get; set; }
        public string titulo { get; set; }
        public string infraestructuraOpcional { get; set; }
        public Nullable<int> idAcademico { get; set; }
        public Nullable<int> idTipoTrabajo { get; set; }
    
        public virtual academico academico { get; set; }
        public virtual tipotrabajo tipotrabajo { get; set; }
    }
}
